version: "3.9"

services:
  api:
    build: ./api
    ports:
      - 3001:3001
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules

    environment:
      - NODE_ENV=development
      - PORT=3001
